import 'package:flutter/material.dart';
import 'package:shoplaza/const/colors.dart';

class Privacy extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: ListView(children: [
          Text(
            'Privacy Policy',
            style: TextStyle(color: redColor, fontSize: 25),
          ),
          SizedBox(
            height: 20,
          ),
          Text(
              "by Telegram 1. IntroductionThis Privacy Policy sets out how we, Telegram Messenger Inc.(“Telegram”), use and protect your personal data that you provide tous, or that is otherwise obtained or generated by us, inconnection with your use of our cloud-based messaging services (the “Services”).Forthe purposes of this Privacy Policy,‘we’, ‘us’ and ‘our’ refers to Telegram, and ‘you’ refers to you, the user of the Services.1.1 Privacy PrinciplesTelegram has two fundamental principles when it comes to collecting and processing private data:We don't use your data to show you ads.We only store the data that Telegram needs to function as a secure and feature-rich messaging service.1.2. Terms of ServiceThis Privacy Policy forms part of our Terms of Service, which describes the terms under which you use our Services and which are available at https://telegram.org/tos. This Privacy Policy should therefore be read in conjunction with those terms.1.3. Table of Contentshow we keep your personal data safewhat we may use your personal data for1.4. EEA RepresentativeIf you live in a country in the European Economic Area (EEA), the Services are provided by Telegram, which for the purposes of applicable data protection legislation is the data controller responsible for your personal data when you use our Services. However, as Telegram is located outside the EEA, we have designated one of our EEA-based group companies, Telegram UK Holdings Ltd (71-75 Shelton Street, Covent Garden, London, England, WC2H 9JQ), as a representative to whom you may direct any issues you have relating to our processing of your personal data.2. Legal Ground for Processing Your Personal DataWe process your personal data on the ground that such processing is necessary to further our legitimate interests (including: (1) providing effective and innovative Services to our users; and (2) to detect, prevent or otherwise address fraud or security issues in respect of our provision of Services), unless those interests are overridden by your interest or fundamental rights and freedoms that require protections of personal data.Telegram is a communication service. You provide your mobile number and basic account data (which may include profile name, profile picture and about information) to create a Telegram account.To make it easier for your contacts and other people to reach you and recognize who you are, the screen name you choose, your profile pictures, and your username (should you choose to set one) on Telegram are always public. We don't want to know your real name, gender, age or what you like.We do not require your screen name to be your real name. Note that users who have you in their contacts will see you by the name they saved and not by your screen name. This way your mother can have the public name 'Johnny Depp' while appearing as 'Mom' to you and as 'Boss' to her underlings at work (or the other way around, depending on how these relationships are structured).3.3. Your Messages3.3.1. Cloud ChatsTelegram is a cloud service. We store messages, photos, videos and documents from your cloud chats on our servers so that you can access your data from any of your devices anytime without having to rely on third-party backups. All data is stored heavily encrypted and the encryption keys in each case are stored in several other data centers in different jurisdictions. This way local engineers or physical intruders cannot get access to user data.Secret chats use end-to-end encryption. This means that all data is encrypted with a key that only you and the recipient know. There is no way for us or anybody else without direct access to your device to learn what content is being sent in those messages. We do not store your secret chats on our servers. We also do not keep any …")
        ]),
      ),
    );
  }
}
